{{- $publicService := .Values.frontend.service.public -}}
{{- $publicServiceEnabled := eq (include "sre-simulator.exposureMode" .) "publicService" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sre-simulator.fullname" . }}-frontend
  labels:
    {{- include "sre-simulator.labels" . | nindent 4 }}
    {{- include "sre-simulator.frontend.selectorLabels" . | nindent 4 }}
  {{- with $publicService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ ternary "LoadBalancer" "ClusterIP" $publicServiceEnabled }}
  {{- if and $publicServiceEnabled $publicService.loadBalancerIP }}
  loadBalancerIP: {{ $publicService.loadBalancerIP | quote }}
  {{- end }}
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      protocol: TCP
  selector:
    {{- include "sre-simulator.frontend.selectorLabels" . | nindent 4 }}
