apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sre-simulator.fullname" . }}-frontend
  labels:
    {{- include "sre-simulator.labels" . | nindent 4 }}
    {{- include "sre-simulator.frontend.selectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      {{- include "sre-simulator.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sre-simulator.frontend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          env:
            - name: BACKEND_INTERNAL_BASE_URL
              value: "http://{{ include "sre-simulator.fullname" . }}-backend:{{ .Values.backend.port }}"
          ports:
            - containerPort: {{ .Values.frontend.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
