---
services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "DevPass@123!"
    ports:
      - "1433:1433"
    healthcheck:
      test: >-
        /opt/mssql-tools/bin/sqlcmd
        -S localhost -U sa -P 'DevPass@123!' -Q 'SELECT 1'
      interval: 10s
      timeout: 5s
      retries: 5
