output "resource_group_name" {
  description = "Resource group containing all resources (delete this to tear everything down)."
  value       = azurerm_resource_group.main.name
}

output "aro_cluster_name" {
  description = "Name of the ARO cluster."
  value       = local.cluster_name
}

output "aro_api_server_url" {
  description = "ARO API server URL."
  value       = jsondecode(azapi_resource.aro_cluster.output).properties.apiserverProfile.url
}

output "aro_console_url" {
  description = "ARO web console URL."
  value       = jsondecode(azapi_resource.aro_cluster.output).properties.consoleProfile.url
}

output "aoai_endpoint" {
  description = "Azure OpenAI endpoint URL."
  value       = azurerm_cognitive_account.openai.endpoint
}

output "aoai_deployment_name" {
  description = "Azure OpenAI deployment name (use as AI_AZURE_OPENAI_DEPLOYMENT)."
  value       = azurerm_cognitive_deployment.model.name
}

output "aoai_account_name" {
  description = "Azure OpenAI account name (for `az cognitiveservices account keys list`)."
  value       = azurerm_cognitive_account.openai.name
}

output "prod_namespace" {
  description = "Fixed namespace for the stable app deployment (shared AOAI, same cluster as e2e)."
  value       = var.prod_namespace
}

# ---------------------------------------------------------------------------
# Azure SQL Database outputs (only when enable_database = true)
# ---------------------------------------------------------------------------
output "sql_server_fqdn" {
  description = "Azure SQL Server FQDN."
  value       = var.enable_database ? azurerm_mssql_server.main[0].fully_qualified_domain_name : ""
}

output "sql_database_name" {
  description = "Azure SQL Database name."
  value       = var.enable_database ? azurerm_mssql_database.app[0].name : ""
}

output "sql_connection_hint" {
  description = "DATABASE_URL template (replace <PASSWORD> with the admin password). Uses ADO.NET-style 'Server=...;Database=...;User Id=...;Password=...' connection string format."
  sensitive   = true
  value       = var.enable_database ? "Server=${azurerm_mssql_server.main[0].fully_qualified_domain_name};Database=${azurerm_mssql_database.app[0].name};User Id=sresimadmin;Password=<PASSWORD>;Encrypt=true;TrustServerCertificate=false" : ""
}

output "env_file_snippet" {
  description = "Paste into backend/.env.local to connect to these resources."
  value = join("", [
    <<-EOT
    # --- Generated by terraform output env_file_snippet ---
    AZURE_SUBSCRIPTION_ID=${data.azurerm_client_config.current.subscription_id}
    ARO_RG=${azurerm_resource_group.main.name}
    ARO_CLUSTER=${local.cluster_name}
    AOAI_RG=${azurerm_resource_group.main.name}
    AOAI_ACCOUNT=${azurerm_cognitive_account.openai.name}
    AOAI_DEPLOYMENT=${azurerm_cognitive_deployment.model.name}
    AI_PROVIDER=azure-openai
    AI_MOCK_MODE=false
    AI_STRICT_STARTUP=true
    AI_MODEL=${var.aoai_model_name}
    AI_AZURE_OPENAI_ENDPOINT=${azurerm_cognitive_account.openai.endpoint}
    AI_AZURE_OPENAI_DEPLOYMENT=${azurerm_cognitive_deployment.model.name}
    AI_AZURE_OPENAI_API_VERSION=2024-10-21
    AI_AZURE_OPENAI_API_KEY=<run: az cognitiveservices account keys list -g ${azurerm_resource_group.main.name} -n ${azurerm_cognitive_account.openai.name} --query key1 -o tsv>
    EOT
    ,
    var.enable_database ? <<-SQL
    # --- Azure SQL Database (enable_database = true) ---
    STORAGE_BACKEND=mssql
    DATABASE_URL=<run: terraform -chdir=infra output -raw sql_connection_hint | sed 's/<PASSWORD>/YOUR_SQL_PASSWORD/'>
    SQL
    : "",
  ])
}

output "post_apply_checklist" {
  description = "Post-apply steps (Geneva suppression, kubeconfig, namespace model, optional SQL)."
  value = join("", [
    <<-EOT

    ╔══════════════════════════════════════════════════════════════════════╗
    ║                       POST-APPLY CHECKLIST                          ║
    ╠══════════════════════════════════════════════════════════════════════╣
    ║                                                                      ║
    ║  1. SILENCE CLUSTER IN GENEVA HEALTH                                 ║
    ║     Create a suppression rule to avoid production alert noise:        ║
    ║     • Scope: Cluster = "${local.cluster_name}"                       ║
    ║     • Resource Group = "${azurerm_resource_group.main.name}"          ║
    ║     • Suppression type = "Suppress all alerts"                       ║
    ║     • Duration = Indefinite (or match cluster lifetime)              ║
    ║     • Reason = "Test/development cluster – not production"           ║
    ║     • Then: export GENEVA_SUPPRESSION_RULE_ACTIVE=true               ║
    ║                                                                      ║
    ║  2. GET KUBECONFIG                                                   ║
    ║     make tf-kubeconfig                                               ║
    ║                                                                      ║
    ║  3. GENERATE .env.local                                              ║
    ║     terraform -chdir=infra output -raw env_file_snippet              ║
    ║                                                                      ║
    ║  4. NAMESPACE MODEL (shared cluster, shared AOAI)                    ║
    ║     • Stable ("prod"):  make prod-up   → ns "${var.prod_namespace}"  ║
    ║     • Ephemeral (e2e):  make e2e-azure-route-up → timestamped ns     ║
    ║     • Both share the same Azure OpenAI account/deployment.           ║
    ║     • prod-down requires typing the namespace name to confirm.       ║
    ║     • e2e namespaces are disposable and auto-cleaned.                ║
    ║                                                                      ║
    ║  5. FINAL DEPLOY + CHECKS (with Azure SQL enabled)                   ║
    ║     • DB_SECRET_NAME=sre-sql-creds make prod-up-final                ║
    ║     • make public-exposure-audit NS="${var.prod_namespace}"           ║
    ║     • make db-port-forward-check NS="${var.prod_namespace}"           ║
    ║                                                                      ║
    EOT
    ,
    var.enable_database ? <<-SQL
    ║  5. AZURE SQL DATABASE (enable_database = true)                      ║
    ║     a. Get the connection string template:                            ║
    ║        terraform -chdir=infra output -raw sql_connection_hint         ║
    ║     b. Replace <PASSWORD> with your sql_admin_password value.         ║
    ║     c. Create a K8s secret in the target namespace:                   ║
    ║        oc -n <NS> create secret generic sre-sql-creds \              ║
    ║          --from-literal=connection-string="Server=...;..."            ║
    ║     d. Deploy with database enabled:                                  ║
    ║        DB_SECRET_NAME=sre-sql-creds make prod-up                      ║
    ║                                                                      ║
    SQL
    : "",
    <<-END
    ╚══════════════════════════════════════════════════════════════════════╝
    END
  ])
}
