-- Consolidated Postgres baseline.
--
-- This is the *final state* of the schema, not a file-for-file translation of
-- the T-SQL lineage in ../migrations/. Those eight files encode the history of
-- an existing Azure SQL database; a new Postgres database has none of it, and
-- replaying it would create-then-drop three indexes and re-type two columns.
--
-- Consolidated from:
--   001_init.sql                      sessions, leaderboard_entries, gameplay_metrics
--   002_auth_and_anonymous_claims.sql players, anonymous_trial_claims, identity columns
--   002_gameplay_lifecycle_events.sql lifecycle_state, command_count, score_total, grade
--   003_gameplay_lifecycle_dedupe.sql ux_gameplay_metrics_session_lifecycle
--   004_traffic_source.sql            traffic_source across all three tables
--   005_session_scenario_context.sql  sessions.scenario_id, sessions.scenario_payload
--   006_platform_dimension.sql        platform across all three tables
--   007_github_login_nickname_length.sql  nickname widened to 39 (GitHub login max)
--
-- Equivalence with the MSSQL schema is guaranteed behaviourally, by the shared
-- contract suite in src/integration/store-contract.ts, which both backends run.
--
-- The PG lineage continues at 002_*.sql; do not edit this file once it has been
-- applied to a real database.

CREATE TABLE IF NOT EXISTS sessions (
  token                      UUID PRIMARY KEY,
  platform                   VARCHAR(16) NOT NULL DEFAULT 'aro-classic'
                               CHECK (platform IN ('aro-classic', 'aro-hcp', 'aks')),
  difficulty                 VARCHAR(10) NOT NULL
                               CHECK (difficulty IN ('easy', 'medium', 'hard')),
  scenario_id                VARCHAR(255),
  scenario_title             VARCHAR(255) NOT NULL,
  scenario_payload           TEXT,
  start_time                 BIGINT NOT NULL,
  used                       BOOLEAN NOT NULL DEFAULT FALSE,
  traffic_source             VARCHAR(16) NOT NULL DEFAULT 'player'
                               CHECK (traffic_source IN ('player', 'automated')),
  identity_kind              VARCHAR(10) NOT NULL DEFAULT 'anonymous',
  github_user_id             VARCHAR(64),
  github_login               VARCHAR(255),
  anonymous_claim_key        VARCHAR(128),
  persistent_score_eligible  BOOLEAN NOT NULL DEFAULT FALSE,
  created_at                 TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_sessions_created
  ON sessions (created_at);
CREATE INDEX IF NOT EXISTS idx_sessions_start_time
  ON sessions (start_time);
CREATE INDEX IF NOT EXISTS idx_sessions_platform_start_time
  ON sessions (platform, start_time);

CREATE TABLE IF NOT EXISTS leaderboard_entries (
  id                   UUID PRIMARY KEY,
  nickname             VARCHAR(39) NOT NULL CHECK (length(btrim(nickname)) > 0),
  platform             VARCHAR(16) NOT NULL DEFAULT 'aro-classic'
                         CHECK (platform IN ('aro-classic', 'aro-hcp', 'aks')),
  difficulty           VARCHAR(10) NOT NULL
                         CHECK (difficulty IN ('easy', 'medium', 'hard')),
  score_efficiency     INTEGER NOT NULL DEFAULT 0,
  score_safety         INTEGER NOT NULL DEFAULT 0,
  score_documentation  INTEGER NOT NULL DEFAULT 0,
  score_accuracy       INTEGER NOT NULL DEFAULT 0,
  score_total          INTEGER NOT NULL DEFAULT 0,
  grade                VARCHAR(5) NOT NULL,
  command_count        INTEGER NOT NULL DEFAULT 0,
  duration_ms          BIGINT NOT NULL,
  scenario_title       VARCHAR(255) NOT NULL,
  traffic_source       VARCHAR(16) NOT NULL DEFAULT 'player'
                         CHECK (traffic_source IN ('player', 'automated')),
  identity_kind        VARCHAR(10),
  github_user_id       VARCHAR(64),
  github_login         VARCHAR(255),
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Partial unique index, not a table constraint: rows without a GitHub identity
-- are anonymous and must not collide with each other. ON CONFLICT against this
-- index has to restate the WHERE clause to be inferrable.
CREATE UNIQUE INDEX IF NOT EXISTS ux_leaderboard_entries_github_platform_difficulty_traffic
  ON leaderboard_entries (github_user_id, platform, difficulty, traffic_source)
  WHERE github_user_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_leaderboard_entries_platform_difficulty_score
  ON leaderboard_entries (platform, difficulty, traffic_source, score_total DESC, duration_ms ASC);

CREATE TABLE IF NOT EXISTS gameplay_metrics (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_token         UUID REFERENCES sessions(token) ON DELETE SET NULL,
  platform              VARCHAR(16) NOT NULL DEFAULT 'aro-classic'
                          CHECK (platform IN ('aro-classic', 'aro-hcp', 'aks')),
  traffic_source        VARCHAR(16) NOT NULL DEFAULT 'player'
                          CHECK (traffic_source IN ('player', 'automated')),
  nickname              VARCHAR(39),
  difficulty            VARCHAR(10),
  scenario_title        VARCHAR(255),
  lifecycle_state       VARCHAR(16) NOT NULL DEFAULT 'completed'
                          CHECK (lifecycle_state IN ('started', 'completed', 'abandoned')),
  command_count         INTEGER NOT NULL DEFAULT 0,
  commands_executed     JSONB DEFAULT '[]'::jsonb,
  scoring_events        JSONB DEFAULT '[]'::jsonb,
  chat_message_count    INTEGER DEFAULT 0,
  ai_prompt_tokens      INTEGER DEFAULT 0,
  ai_completion_tokens  INTEGER DEFAULT 0,
  duration_ms           BIGINT,
  score_total           INTEGER,
  grade                 VARCHAR(5),
  completed             BOOLEAN DEFAULT FALSE,
  metadata              JSONB DEFAULT '{}'::jsonb,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- One lifecycle event of each kind per session. The duplicate-key violation is
-- load-bearing: PgMetricsStore.recordGameplay swallows exactly this constraint.
CREATE UNIQUE INDEX IF NOT EXISTS ux_gameplay_metrics_session_lifecycle
  ON gameplay_metrics (session_token, lifecycle_state)
  WHERE session_token IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_metrics_nickname
  ON gameplay_metrics (nickname);
CREATE INDEX IF NOT EXISTS idx_metrics_created
  ON gameplay_metrics (created_at);
CREATE INDEX IF NOT EXISTS idx_metrics_session_created
  ON gameplay_metrics (session_token, created_at);
CREATE INDEX IF NOT EXISTS idx_metrics_lifecycle_state
  ON gameplay_metrics (lifecycle_state, created_at);
CREATE INDEX IF NOT EXISTS idx_metrics_traffic_source_created
  ON gameplay_metrics (traffic_source, created_at);
CREATE INDEX IF NOT EXISTS idx_metrics_traffic_source_platform_session_created
  ON gameplay_metrics (traffic_source, platform, session_token, lifecycle_state, created_at DESC, id DESC);

CREATE TABLE IF NOT EXISTS players (
  github_user_id  VARCHAR(64) PRIMARY KEY,
  github_login    VARCHAR(255) NOT NULL,
  display_name    VARCHAR(255) NOT NULL,
  avatar_url      VARCHAR(1024),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS anonymous_trial_claims (
  claim_key      VARCHAR(128) PRIMARY KEY,
  created_at_ts  BIGINT NOT NULL,
  expires_at_ts  BIGINT NOT NULL,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_anonymous_trial_claims_expires_at
  ON anonymous_trial_claims (expires_at_ts);
