---
name: Pre-commit Checks

"on":
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Harden runner
        # v2.21.0
        uses: >-
          step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c
        with:
          egress-policy: audit

      - name: Checkout
        # v6.0.2
        uses: >-
          actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Setup Bun toolchain
        uses: ./.github/actions/setup-bun-toolchain

      - name: Ensure SHA-pinned actions
        # v5.0.3
        uses: >-
          zgosalvez/github-actions-ensure-sha-pinned-actions@3db98c0363e2fa5df3e1c4c471777a7c10b24cc9

      - name: Install pre-commit
        run: python3 -m pip install --upgrade pre-commit

      - name: Install dependencies
        run: make install

      - name: Run pre-commit hooks
        run: make pre-commit
